# -*- coding: utf-8 -*-
"""ACTIVIDAD 1 SEMANA TEC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMWb_x3TB92Uq9LT_ZgEyyGK6xA8dyB6
"""

import cv2
import matplotlib.pyplot as plt

img=cv2.imread("/act1.jpg")

print(img)

#Matrices en RGB Y HSV
img_hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
img_rgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

print(img_hsv)

plt.imshow(img)

print(img_rgb)

#print(img_hsv)
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.title("RGB")
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

plt.axis("off")

plt.subplot (1,2,2)
plt.title("HSV")
plt.imshow(cv2.cvtColor(img_hsv,cv2.COLOR_HSV2RGB))

plt.subplot(1,2,1)
plt.title("RGB")
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.subplot (1,2,2)
plt.title("HSV")
plt.imshow(cv2.cvtColor(img_hsv,cv2.COLOR_HSV2RGB))
plt.axis("off")

img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img_inverted = cv2.bitwise_not(img)

import numpy as np
#Definir rango de amarillo en RGB
lower_yellow = np.array([180,180,0],dtype=np.uint8)
upper_yellow = np.array([255,255,120],dtype=np.uint8)

#Crear máscara (en RGB)
mask = cv2.inRange(img_rgb,lower_yellow,upper_yellow)

#Aplicar máscara a la imagen original
result = cv2.bitwise_and(img_rgb,img_rgb,mask=mask)
img_gray_rgb = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2RGB)
final_result = cv2.addWeighted(img_gray_rgb,1,result,1,0)

#Mostrar resultados
plt.figure(figsize=(15,5))

plt.subplot(1,5,1)
plt.title("Original")
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.subplot(1,5,2)
plt.title("RGB")
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.subplot (1,5,3)
plt.title("HSV")
plt.imshow(cv2.cvtColor(img_hsv,cv2.COLOR_HSV2RGB))
plt.axis("off")
plt.subplot (1,5,4)
plt.title("Mask")
plt.imshow(result)
plt.axis("off")
plt.subplot(1,5,5)
plt.title("Filtro")
plt.imshow(final_result)
plt.axis("off")

#Morado HSV
bajo_morado = np.array([128,100,50])
alto_morado = np.array([142,255,255])

#crear máscara
mascara_morado = cv2.inRange(img_hsv,bajo_morado,alto_morado)

#aplicar máscara
resultado_morado = cv2.bitwise_and(img_rgb,img_rgb,mask=mascara_morado)

#mostrar resultados
plt.imshow(resultado_morado)

#aplicar máscara a imágen orginal
resultado_morado = cv2.bitwise_and(img_rgb,img_rgb,mask=mascara_morado)
img_gray_rgb = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2RGB)
final_result2 = cv2.addWeighted(img_gray_rgb,1,resultado_morado,1,0)

plt.imshow(final_result2)

plt.subplot(1,6,1)
plt.title("Original")
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.subplot(1,6,2)
plt.title("RGB")
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.subplot (1,6,3)
plt.title("HSV")
plt.imshow(cv2.cvtColor(img_hsv,cv2.COLOR_HSV2RGB))
plt.axis("off")
plt.subplot (1,6,4)
plt.title("Mask")
plt.imshow(result)
plt.axis("off")
plt.subplot(1,6,5)
plt.title("Filtro")
plt.imshow(final_result)
plt.axis("off")
plt.subplot(1,6,6)
plt.title("Mask2")
plt.imshow(final_result2)
plt.axis("off")

